// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKfeprLQP3Bu4so0Ydf9-EBKn5uPz4VUU',
    appId: '1:64457253016:web:6d1685bcd20217093870ed',
    messagingSenderId: '64457253016',
    projectId: 'jaziratalakarm-4d0ab',
    authDomain: 'jaziratalakarm-4d0ab.firebaseapp.com',
    databaseURL: 'https://jaziratalakarm-4d0ab-default-rtdb.firebaseio.com',
    storageBucket: 'jaziratalakarm-4d0ab.firebasestorage.app',
    measurementId: 'G-NPP2Y6GTB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1_E1K92d-ww80SuPQHhSXGGIf36Tgv8A',
    appId: '1:64457253016:android:e124f60b025f9f3c3870ed',
    messagingSenderId: '64457253016',
    projectId: 'jaziratalakarm-4d0ab',
    databaseURL: 'https://jaziratalakarm-4d0ab-default-rtdb.firebaseio.com',
    storageBucket: 'jaziratalakarm-4d0ab.firebasestorage.app',
  );
}
